version: '3.1'

services:
  front:
    image: oncharterliz/multi-frigate:latest
    volumes:
      - /etc/timezone:/etc/timezone:ro # for Unix TZ
      - /etc/localtime:/etc/localtime:ro # for Unix Time
    environment:
      FRIGATE_PROXY: http://localhost:4000
      OPENID_SERVER: https://server:port/realms/your-realm
      CLIENT_ID: frontend-client
    ports:
      - 80:80 # set your port here
    depends_on:
      - backend      

  backend:
    image: oncharterliz/frigate-proxy:latest
    restart: unless-stopped
    volumes:
      - /etc/timezone:/etc/timezone:ro # for Unix TZ
      - /etc/localtime:/etc/localtime:ro # for Unix Time
    environment:
      SERVER: http://0.0.0.0:4000
      DATABASE_URL: "mongodb://db-username:db-password@mongo:27017/db-name?retryWrites=true&w=majority&authSource=admin"
      ENCRYPTION_KEY: 'YOUR_SUPER_SECRET_KEY_FOR_ENCRYPTED_SETTINGS'
      LOG_LEVEL: debug
      RATE_LIMIT: 100 # optional, requests rate limit per TIME_WINDOW, default 1000
      TIME_WINDOW: 60000 # optional, requsts time window, default 60000
    ports:
      - 4000:4000
    depends_on:
      - mongo

  # Mongo in replica set mode. Backend works with only replica set mongo db
  # connect with compass at direct connection mode, e.g mongodb://user:password@localhost:27017/?authSource=admin&directConnection=true
  mongo:
    image: mongo:7.0.6
    command: ["/bin/bash", "/docker-entrypoint-initdb.d/init-mongo-set.sh"]
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - ./mongodb/data:/data/db
      - ./keyfile:/opt/keyfile # Don't forget to create or add keyfile, e.g. `openssl rand -base64 756 > keyfile`
      - ./init-mongo-set.sh:/docker-entrypoint-initdb.d/init-mongo-set.sh # mongo set init script
    environment:
      REPLICA_SET_ADMIN_NAME: db-username
      REPLICA_SET_ADMIN_PASSWORD: db-password
      REPLICA_SET_ID: rs0
      REPLICA_SET_NUMBER: 0
      REPLICA_SET_HOST: mongo # must be equal to docker host image name for internal communication
      REPLICA_SET_PORT: 27017 # must be equal to docker port name for internal communication
      MONGO_APP_DATABASE: db-name
    restart: unless-stopped